# Collaboration
Throughout the development cycle of site maps, the contributions and participation of the different stakeholders identified earlier in this guide, is key to producing high quality, updated site maps. 
Static PDF site maps are the main output of this workflow. However, it is also important to recognise that other products are created in the process of making site maps, such as:

 - Aerial/ Satellite imagery of sites in which CCCM, shelter or other humanitarian activities are being carried out,
 - Spatial database of the site environement and its infrastructure,
 - GeoPDFs,
 - Site map template

## Information and knowledge management
These are valuable information products which can be used by colleagues and other humanitarian actors to inform conduct thematic analysis as well as serve as an evidence base for advocacy, planning and decision making. 

More importantly, these products are tools to collaborate with stakeholders and actors on the ground that in turn can:
 
1. Verify and validate the information, 
2. Feedback and suggest modifications,
3. Update the data when changes occur on the ground. 

Therefore, the manner in which this data is stored, presented and shared is crucial to both allow for and promote the use of site maps. 

:::{.callout-note}
## Note
IOM and partner agency/ NGO staff can and are encouraged to share these data products with the CCCM Global Cluster so there is continuity in the management of site data. The CCCM Global cluster can play a role in facilitating the storage, dissemination and use of site data whilst ensuring it is done so responsibly. 
:::

## Interoperability of GIS and CAD data
GIS and CAD interoperability is key to developing sustainable site data lifecycles. Whilst both can be used to create spatial data layers and produce maps, each software has distinct uses and advantages. These are summarised in the table below:

| CAD | GIS |
|-------|--------|
|Design and Drafting tool|Data gathering, display and analysis tool|
|Allows for survey-level precision|Allows for attributes/ information to describe features|
|Produce construction documentation and plans|Conduct data analysis and display data/ produce thematic maps|

Whilst this guide accompanies site mappers through the process of creating maps using GIS software, some mappers may have a preference for CAD software or some exisiting site data may be in CAD format. CAD files and data can be used to generate data layers in GIS systems however this depends on the CAD files conforming to the following standards:
- the data must be cleaned and free from drafting errors
- each layer must contain only one type of geometry
- the dataset comes with metadata (information about a database typically in a XML or HTML doc: list of layers, coordinate system, scaling factors etc)
- the file does not contain 'extra' uneccessary layers
- the data must be either in real-world units or if the scaling factor is provided in the metadata

Similarly, data in GIS or the dataset generated in the proccess of analysing and compiling the data into site maps can be exported into CAD for site planning purpose. 

## Generating, reading and annotating geoPDFs
In the previous section, we looked at exporting print layouts as GeoPDFs. GeoPDFs are PDFs with embedded georeferenced location information. 

GeoPDFs can be imported into [Avenza maps](https://www.avenzamaps.com/mobile-maps?campaignid=10221828697&adgroupid=102940455500&adid=453328850375&gclid=Cj0KCQiAg_KbBhDLARIsANx7wAxTp38Kmz11Ou-eCXzYSF_EkQpvBq3PvAo3sxuIS88hZMkaglVMWSAaAtEFEALw_wcB). The app uses the built in GPS in a tablet or smartphone to locate users when out of range of a network or internet connection. Users can mark points of interest, attach photos with exact location, and add annotations to existing features. 

## Gathering feedback and map iterations
Through Focus group discussions and site walks, the site maps can be annotated by different stakeholders to mark for example, errors in the map, changes in the layout of the site, the location of new or closed services etc. The site map can either be project or printed in large formats or imported in Avenza map to be used during site walks in order to determine the precise location of different features.  

## Using Site maps in Practice
Site maps can provide a spatial perspective on issues and risks within sites. They can be used as inputs to safety audits, identification of risk factors and support coordinated planning and coordination of response activities. 



