# Tracing and labeling

Once the aerial imagery has been obtained, two primary post-processing approaches are involved to extract the geographic information of different site features from the imagery. The site mapper can either **manually** or **automatically** trace and label site features. The site features that will be extracted from the aerial imagery will depend on the specific needs for, objectives and audience of the site map. 

For instance, the site mapper may look to map the location and configuration of shelters in a site. Post-processing of the image will consist of generating a new data layer of shelter outlines.

It is important to be aware of the advantages and the disadvantages of choosing whether to manually or automatically trace and label site features in order to determine which option is most suited. The table below presents a summary of both.

| Manual | Automatic|
|-------|--------|
| **Advantages** <br><br> Extracting geographic information by manually tracing and labeling requires only basic GIS skills. <br><br> It can be done offline in contexts with limited connectivity. <br><br> Allows for medium to high accuracy of traced shelters and buildings that have irregular or non-rectangular geometry. | <br><br> A high number of shelters and buildings can be traced and labelled in a small amount of time, relative to manual tracing.|
|**Disadvantages** <br><br> Time intensive, relative to automatic tracing. | <br><br> Most open-source tools require some minimum understanding of machine learning principles. <br><br> Most low-code tools are not open-source and may incur additional costs <br><br> Depending on 1) how much data is available to train the machine learning model, 2) the type and accuracy of the tool used (amongst other factors), there may be errors or inaccuracies in the outlines and labels generated requiring the site mapper to manually verifying and edit outputs.|

::: callout-note
# Note

If there is high cloud or tree coverage, some features may not be visible in the aerial imagery and thus will not be visible to the site mapper or detected by the machine learning model. Therefore, it is crucial to validate all extracted geographic information by consulting with and seeking inputs from stakeholders and colleagues in the field.
:::

## Manual tracing

Manual tracing can be done in GIS or AutoDesk software. QGIS can be downloaded for free [here](https://www.qgis.org/en/site/forusers/download.html). Once the software download is complete, [georeference](https://www.qgistutorials.com/en/docs/3/advanced_georeferencing.html) the aerial imagery into a new workspace. Create a [new vector layer](https://docs.qgis.org/3.22/en/docs/training_manual/create_vector_data/create_new_vector.html#:~:text=Open%20QGIS%20and%20create%20a,to%20define%20a%20new%20layer.) and [toggle edit](https://docs.qgis.org/2.8/en/docs/user_manual/working_with_vector/editing_geometry_attributes.html#digitizing-an-existing-layer) to trace the required features and save the data layer. 

## Automatic tracing

Below are some tools which can assist you in creating a workflow for automatic shelter detection: 

- Create a training data set from aerial imagery with [Groundwork.azavea](https://groundwork.azavea.com/). When signing up with Groundwork, up to 10 campaigns (projects) can be created free of charge when creating an account. Upload orthomosaic image to Groundwork, label features and export the training data in .json format. 

- Extract shelter outlines from aerial imagery using [Mapflow.ai](https://mapflow.ai/)'s built in deep learning and semantic segmentation models. After signing up, create a new project. Mapflow can also be used as a plugin in QGIS and can be downloaded from [here](https://plugins.qgis.org/plugins/mapflow/). Further guidance on how to install the Mapflow QGIS plugin is available [here](https://docs.mapflow.ai/api/qgis_mapflow#user-interface). 

::: {.callout-warning}
## Tiff vs GeoTiff
In order to use your orthomosaic in Mapflow.ai, you may need to [georeference your image](https://docs.qgis.org/3.28/en/docs/user_manual/working_with_raster/georeferencer.html) in QGIS beforehand and export it as a GeoTiff with either web mercator, UTM or lat-lon coordinate systems. 
:::

- Segment GeoTIFF files using Segment Anything Model and save segmentation results in vector format with [SamGeo's Automatic Mask Generator notebook](https://colab.research.google.com/github/opengeos/segment-geospatial/blob/main/docs/examples/automatic_mask_generator.ipynb). This video tutorial takes you through how to use this notebook [here](https://www.youtube.com/watch?v=YHA_-QMB8_U&ab_channel=QiushengWu). 
