# Identifying requirements
Producing site maps requires a significant investment of personnel, time, software and hardware. In addition to these, the political/security/conflict context of the area, as well community acceptance and regulatory framework are factors to consider in whether or not site maps can be developed in your context and if so, which approach is most feasible.

Before jumping into **how** to develop site maps, it is important to first assess **if they can or should** be developed:

1. Are site maps needed in your context and what activities or decisions will they inform?

2. What stakeholders need to be involved, both in the development of the site maps (affected population, local and national authorities, staff, etc) and in their use (CCCM actors, local authorities, etc)? *How will buy in from these stakeholders be ensured?*

4. What is required to develop site maps in your context? Regardless of the chosen approach, the development of site maps requires funding, personnel, time, hardware, software, and connectivity. A shortcoming on any of these may affect the feasibility or timeline of the development of site maps.

5. What red-line contextual challenges, risks and sensitivities exist or may arise during the development of the site maps that could affect the overall feasibility or appropriateness of their development?

## Stakeholders
Whilst the development of site maps should be approach and context dependent, typically the following stakeholders will be involved:

- **Affected population in sites.** These need to be consulted before collecting drone-captured imagery to make sure they are informed and consent to the activity in order to minimize risks associated with this approach and prevent any misunderstandings.

- **Humanitarian actors.** These can help inform which and how many sites need to be mapped. Humanitarian actors, especially those on the ground, will also feed into the iteration process of the site maps, in order to validate geographic information and keep the maps and the underlying data layers up to date. 

- **Authorities.** The authorities are a crucial interlocutor for approvals. In addition, their engagement can promote the use of the site maps in decision making processes. The participation of authorities in the site mapping process will also facilitate the handover and long term management of information, expertise and equipment, or support capacity development initiatives for future scenarios.

- **Legal team.** IOM Legal colleagues will provide any additional guidance on data collection, processing and sharing related to your specific context and are responsible for providing the final approval on the use of drones. 

## General Requirements
Developing site maps typically requires the following:

### Personnel
Staff with relevant skills and expertise, as well as support staff such as drivers and procurement support will be needed. Depending on the number of sites and how quickly the site maps are needed, the site mapping team may need to be scaled up. 

### Time
Developing site maps can be a time-intensive process, requiring prior consultations with various stakeholders, lead-time for procurement of equipment, travel time for site visits, time for collecting and processing the imagery, composing the site maps and collaboratively iterating or updating their content. These are important factors to consider when looking at the time frame of their intended use.

### Hardware and Software
Depending on the chosen approach, not all items in the below table will be required. Highlighted are items which are required regardless of the chosen approach:

|Hardware|Software|
| ---- | ------- |
|Laptop|QGIS (or other GIS software)|
|Drone kit| WedODM |
|Android Tablet|Avenza maps|

### Connectivity
While connectivity requirements vary depending on the chosen approach, some degree of connectivity should be assumed as needed. In situations of sudden onset disasters, connectivity can be very challenging and quite often can lead to bottlenecks and delays.

### Funding
There are a series of finanical costs involved in the development of site maps that need to be taken into account. Annex 4 provides a table that can provide indicative figures for the purpose of costing a site mapping exercise. 

### Context
The security, political and regulatory environment play a large role in determining the approach to site mapping in a country but also whether or not the process is feasible at all. Identification of these challenges and risks is best done as early as possible to avoid wasting resources or to allow sufficient time to mitigate them.
